### ISSUE TITLE
Differences in output for some special time zones

### ISSUE THREAD

**Issue by mathieuprog** [smartrent/zoneinfo#18]
I have set up a repo that performs time zone operations for a huge amount of date times:
https://github.com/mathieuprog/tzdb_test

The resulting date times are written into a file per library and can be compared with a diff tool.

It seems that Zoneinfo has some inconsistencies, but it seems only special time zones are affected, such as CST6CDT, EST5EDT, EET, etc. (in europe and northamerica files).

Could you have a look?

**Comment by fhunleth** [comment]
Those are legacy timezone names (since 2005, I think). I'm sure there's a reasonable explanation on why the difference exists due to their ambiguity. Perhaps your system follows [America/New_York](https://github.com/eggert/tz/blob/main/northamerica#L357-L362) for [EST5EDT](https://github.com/eggert/tz/blob/aaca8fad7b6b9334f084734cce2782443d609570/northamerica#L203) for "reasons" even though if you were to follow the database exactly, EST5EDT would be a more boring timezone.

You can check out the regression tests for this library to see the comparison. I view `tz` as truth since whenever I've found an issue and dug into it, that library has been right. If there's a discrepancy with one of the contemporary time zone names, please let us know which one and a bad date/time.

**Comment by mathieuprog** [comment]
I have seen discrepancies in the year 2038 for normal time zones. But if I recall correctly you mentioned that that was to be expected because of the known 2038 bug some software have.

**Comment by fhunleth** [comment]
There's also an issue as to how far in the future the OS maintainer calculates their `tzif` files. 2038 sounds really suspicious, but it could be that your OS maintainer just stopped calculating timezone data after 2038. We'd have to look at the `tzif` file. `zoneinfo` doesn't currently extrapolate accurately past what's specified in the `tzif` files. For our use case, it didn't matter, since it was sufficiently far in the future for all dates we used. That could be improved.

**Comment by mathieuprog** [comment]
I don't think it's suspicious:
https://en.wikipedia.org/wiki/Year_2038_problem
I guess some old 32bit soft is used for calculations.
